server:
  port: 9527
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blog_system?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: tse@9527
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      # \u8FDE\u63A5\u6C60\u6700\u5C0F\u7A7A\u95F2\u8FDE\u63A5\u6570
      minimum-idle: ${SPRING_DATASOURCE_MINIMUM_IDLE:20}
      # \u8FDE\u63A5\u6C60\u5141\u8BB8\u7684\u6700\u5927\u8FDE\u63A5\u6570
      maximum-pool-size: ${SPRING_DATASOURCE_MAXIMUM_POOL_SIZE:200}
      # \u7B49\u5F85\u8FDE\u63A5\u6C60\u5206\u914D\u8FDE\u63A5\u7684\u6700\u5927\u65F6\u957F\uFF08\u6BEB\u79D2\uFF09
      connection-timeout: ${SPRING_DATASOURCE_CONNECTION_TIMEOUT:30000}
  redis:
    host: ${SPRING_REDIS_HOST:localhost}
    port: ${SPRING_REDIS_PORT:6379}
    database: ${SPRING_REDIS_DATABASE:0}
    password: ${SPRING_REDIS_PASSWORD:}
    timeout: 5000
    lettuce:
      pool:
        # \u8D44\u6E90\u6C60\u4E2D\u6700\u5927\u8FDE\u63A5\u6570
        # \u9ED8\u8BA48\uFF0C-1\u8868\u793A\u65E0\u9650\u5236\uFF1B\u53EF\u6839\u636E\u670D\u52A1\u5E76\u53D1redis\u60C5\u51B5\u53CA\u670D\u52A1\u7AEF\u7684\u652F\u6301\u4E0A\u9650\u8C03\u6574
        max-active: ${SPRING_REDIS_POOL_MAX_ACTIVE:50}
        # \u8D44\u6E90\u6C60\u8FD0\u884C\u6700\u5927\u7A7A\u95F2\u7684\u8FDE\u63A5\u6570
        # \u9ED8\u8BA48\uFF0C-1\u8868\u793A\u65E0\u9650\u5236\uFF1B\u53EF\u6839\u636E\u670D\u52A1\u5E76\u53D1redis\u60C5\u51B5\u53CA\u670D\u52A1\u7AEF\u7684\u652F\u6301\u4E0A\u9650\u8C03\u6574\uFF0C\u4E00\u822C\u5EFA\u8BAE\u548Cmax-active\u4FDD\u6301\u4E00\u81F4\uFF0C\u907F\u514D\u8D44\u6E90\u4F38\u7F29\u5E26\u6765\u7684\u5F00\u9500
        max-idle: ${SPRING_REDIS_POOL_MAX_IDLE:50}
        # \u5F53\u8D44\u6E90\u6C60\u8FDE\u63A5\u7528\u5C3D\u540E\uFF0C\u8C03\u7528\u8005\u7684\u6700\u5927\u7B49\u5F85\u65F6\u95F4(\u5355\u4F4D\u4E3A\u6BEB\u79D2)
        # \u9ED8\u8BA4 -1 \u8868\u793A\u6C38\u4E0D\u8D85\u65F6\uFF0C\u8BBE\u7F6E5\u79D2
        max-wait: ${SPRING_REDIS_POOL_MAX_WAIT:5000}
  thymeleaf:
    cache: false
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath*:mapper/*.xml

logging:
  level:
    org.apache.ibatis: ${LOGGING_LEVEL:debug}
    com.github.codingdebugallday.blog: ${LOGGING_LEVEL:debug}