spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cus_spring?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: tse@9527
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      # \u8FDE\u63A5\u6C60\u6700\u5C0F\u7A7A\u95F2\u8FDE\u63A5\u6570
      minimum-idle: ${SPRING_DATASOURCE_MINIMUM_IDLE:20}
      # \u8FDE\u63A5\u6C60\u5141\u8BB8\u7684\u6700\u5927\u8FDE\u63A5\u6570
      maximum-pool-size: ${SPRING_DATASOURCE_MAXIMUM_POOL_SIZE:200}
      # \u7B49\u5F85\u8FDE\u63A5\u6C60\u5206\u914D\u8FDE\u63A5\u7684\u6700\u5927\u65F6\u957F\uFF08\u6BEB\u79D2\uFF09
      connection-timeout: ${SPRING_DATASOURCE_CONNECTION_TIMEOUT:30000}
  jpa:
    show-sql: true
  redis:
    host: ${SPRING_REDIS_HOST:localhost}
    port: ${SPRING_REDIS_PORT:6379}
    database: ${SPRING_REDIS_DATABASE:0}
    password: ${SPRING_REDIS_PASSWORD:}
    timeout: 5000
    lettuce:
      pool:
        # 资源池中最大连接数
        # 默认8，-1表示无限制；可根据服务并发redis情况及服务端的支持上限调整
        max-active: ${SPRING_REDIS_POOL_MAX_ACTIVE:50}
        # 资源池运行最大空闲的连接数
        # 默认8，-1表示无限制；可根据服务并发redis情况及服务端的支持上限调整，一般建议和max-active保持一致，避免资源伸缩带来的开销
        max-idle: ${SPRING_REDIS_POOL_MAX_IDLE:50}
        # 当资源池连接用尽后，调用者的最大等待时间(单位为毫秒)
        # 默认 -1 表示永不超时，设置5秒
        max-wait: ${SPRING_REDIS_POOL_MAX_WAIT:5000}
  http:
    encoding:
      force-response: true
#  cache:
#    redis:
#      time-to-live: 60000