spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cus_spring?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: tse@9527
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      # \u8FDE\u63A5\u6C60\u6700\u5C0F\u7A7A\u95F2\u8FDE\u63A5\u6570
      minimum-idle: ${SPRING_DATASOURCE_MINIMUM_IDLE:20}
      # \u8FDE\u63A5\u6C60\u5141\u8BB8\u7684\u6700\u5927\u8FDE\u63A5\u6570
      maximum-pool-size: ${SPRING_DATASOURCE_MAXIMUM_POOL_SIZE:200}
      # \u7B49\u5F85\u8FDE\u63A5\u6C60\u5206\u914D\u8FDE\u63A5\u7684\u6700\u5927\u65F6\u957F\uFF08\u6BEB\u79D2\uFF09
      connection-timeout: ${SPRING_DATASOURCE_CONNECTION_TIMEOUT:30000}
  jpa:
    show-sql: true
  http:
    encoding:
      force-response: true